[package]
name = "mesh-sync"
version = { workspace = true }
edition = { workspace = true }
license       = { workspace = true }

[dependencies]
cosmwasm-std     = { workspace = true }
cosmwasm-schema  = { workspace = true }
serde        = { workspace = true }
schemars        = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
cw-storage-plus     = { workspace = true }
itertools = "0.10.5"


