[package]
name = "mesh-mocks"
version = { workspace = true }
edition = { workspace = true }
license       = { workspace = true }

[dependencies]
sylvia = { workspace = true }
cosmwasm-std     = { workspace = true }
cosmwasm-schema  = { workspace = true }
cw-utils     = { workspace = true }
cw-storage-plus     = { workspace = true }
mesh-apis     = { workspace = true }

thiserror        = { workspace = true }
serde            = { workspace = true }

